### ISSUE TITLE
Usable driver?

### ISSUE THREAD

**Issue by altayhunter** [galundin/circular-scrolling-improved#1]
I really like this idea and the demo works quite well. Is there a corresponding driver that can be installed, or is this project just meant to inspire someone else to create one?

**Comment by galundin** [comment]
Thanks! Yes, I modified the xfree86-driver-synaptics source to implement these changes to circular scrolling, along with some further refinements. I was pretty happy with the "feel" of it. But the maintainer informed me that the driver is on permanent feature freeze, since the developers had turned their attention toward Weston, so he declined to merge. That was 2 years ago, and I haven't followed the state of development since then. I don't even use the touchpad any more these days. But I'd be happy to dig out the patch, if you're willing and able to recompile the driver from source. I recall it was a bit tricky, but I don't really remember the details....

**Comment by altayhunter** [comment]
Wow, I figured it was abandoned after the demo was made. I would love to get a copy of the patch/source if you can find it. I haven't done much work with driver-level code, but I'll definitely give it a shot. It'd be awesome to actually get it working on my laptop.

**Comment by galundin** [comment]
Sorry I took a few days, it was on a partition I seldom boot.

I went ahead and rebased the patch from the latest master, which you can clone from here:
git://anongit.freedesktop.org/xorg/driver/xf86-input-synaptics

I just dumped the patch in a Gist:
https://gist.github.com/galundin/736d7331a626a0deda13

This code wasn't ready for prime-time, but it met my own needs, and I quit working on it when the maintainer said the driver was on permanent feature-freeze. You're actually the first person who ever expressed an interest in it. :D  

One big caveat: normal edge-scrolling behavior doesn't work when circular scrolling is enabled under this patch. It only responds to circular movement, not linear movement in the edge zones. I was planning to implement that transition with interpolation, to behave just like the proprietary feature, but I never got around to it. So that's a bit annoying to get used to at first, if you're already accustomed to edge-scrolling, but it does provide a much better experience than the existing implementation of circular scrolling.

You have to "engage" scrolling mode by entering the pad from the edge zone. After that, your circular motion can drift anywhere on the pad. As soon as you release your finger, it returns to normal pointer mode, until the next time you begin a touch in the edge zone.

You'll probably need to calibrate the CircScrollDelta parameter. I think the default was 0.1 for the old implementation, but 1.0 is more appropriate for the new one. You could experiment with different values to see what feels best. Here's some documentation for that:

http://linux.die.net/man/5/synaptics
http://linux.die.net/man/1/synclient

Of course, you have to build and install it first:

```
./autogen.sh
./configure && make
sudo make install
```

There might be some dependencies you'll have to meet.... The latest version is complaining about libevdev. I don't really have time to deal with it right now just for testing purposes.... Hopefully you won't have too much problem with it.

Then you actually have to restart to get it to load the new driver:
http://unix.stackexchange.com/questions/37266/reload-xserver-xorg-input-mouse
(That was a frustrating hassle for development iteration.)

Then cross your fingers, and it might just work! :D
Don't forget to calibrate CircScrollDelta.
Let me know if you run into any snags and I'll see what I can do to help.

**Comment by altayhunter** [comment]
Thanks for the thorough write-up. I didn't run into many snags; I just had to install the packages `xorg-util-macros` and `xorg-server-devel` to get it to build. Strangely though, it isn't behaving any differently after I rebooted. The `autogen`, `configure`, `make`, and `make install` all went off without a hitch, but nothing's changed. I also changed CircScollDelta to 1.0 in my Xorg configuration and I have noticed that change.
Before you ask, I definitely applied the patch before building and verified that the changes to `synaptics.c` and `synapticsstr.h` were applied. Here's a [copy of my Xorg configuration](http://pastebin.com/yxvYt7x6); perhaps I need to change the name of the driver or add/remove an option?

**Comment by altayhunter** [comment]
I tried uninstalling the xf86-input-synaptics package I previously had installed through my distro's package manager and rebuilding & reinstalling the modified driver. For some reason Xorg seems to be unable to find the modified driver. Here's some of the output from my Xorg.0.log:

```
[  1706.124] (II) LoadModule: "synaptics"
[  1706.124] (WW) Warning, couldn't open module synaptics
[  1706.124] (II) Unload module: "synaptics"
[  1706.124] (II) Unloading synaptics
[  1706.124] (EE) Failed to load module "synaptics" (module does not exist, 0)
[  1706.124] (EE) No input driver matching 'synaptics'
```

**Comment by altayhunter** [comment]
After pouring over the [man pages of xorg](http://www.x.org/archive/X11R7.5/doc/man/man1/Xorg.1.html) as well as the [output of make install](http://pastebin.com/mQptrhz8) I finally noticed that the install script had placed the module in `/usr/local/lib/xorg/modules`, and Xorg expected them in:

```
$ Xorg -showDefaultModulePath
/usr/lib/xorg/modules
```

I'm not sure how that "local" snuck in there; I guess configure.sh was having a bad day.
Anyway, I didn't want to move stuff around too much, so I just remedied the issue with a couple symbolic links, and all is well now:

```
sudo ln -s /usr/local/lib/xorg/modules/input/synaptics_drv.la /usr/lib/xorg/modules/input/synaptics_drv.la
sudo ln -s /usr/local/lib/xorg/modules/input/synaptics_drv.so /usr/lib/xorg/modules/input/synaptics_drv.so
```

I see what you mean about having to get used to the lack of edge scrolling now. I use circular scrolling so much I didn't think notice, but it will take a bit of getting used to. It's still a _huge_ improvement over the circular scrolling in the official package.
Also, a CircScrollDelta of 1.0 is _way_ too slow on my computer. Even 0.1 is a tad slow; I'll have to tweak it a bit to find what's just right.
Thanks so much for the patch!

**Comment by galundin** [comment]
Sure! Glad you got it working, and thanks for the feedback!

I remember now, I spent a long time troubleshooting the same issue. Sorry I forgot to mention it.

The "technique" I settled on was to quickly swipe inward from the edge, perpendicular to the normal direction of movement, simply to get onto the pad with scrolling mode engaged, and then quickly transition to circular movement. That's adequately efficient, and eliminates the jarring experience of its non-responsiveness to normal linear movement in the edge zone.

Also, the original implementation did not allow horizontal scrolling with the circular gesture. I recall seeing remnants of a partial implementation in the code, but currently only vertical scrolling is supported. That was another improvement I had intended to make, but alas, the whole driver has been declared end-of-life. (Even though the entire userbase of touchpad users still use it.... Ah well.)

**Comment by altayhunter** [comment]
Wait, xf86-input-synaptics is end-of-life? Are the intending to replace it with a different driver, or trying to do some sort of code freeze? If Synaptics had open sourced their official driver it would make sense to me, but in the absence of that it seems bizarre.

If I feel inspired I might take a look at src/synaptics.c at some point to see if I can make any further improvements. I was surprised by how small the patch was as well as how straightforward the code looks.

**Comment by galundin** [comment]
That was my understanding. Not just the driver, but the entire Xfree86 server, more or less. The code is massively bloated with three decades of obsolete features that can't be removed because of the sacredness of strict backward-compatibility. Its architecture has some major flaws that have been hacked around endlessly, but the developers had basically given up on extending it any further. They were working on its replacement, Weston, the reference implementation of the Wayland protocol:
http://wayland.freedesktop.org/

I'm not sure if that accurately represents the consensus opinion of the entire community, but it's certainly the impression I was given by the developer who maintains most of the xf86 input drivers. He said he was only willing to merge bug fixes.

That was the state of things 2 years ago, but like I said, I haven't been following the development at all, so I have no idea where they're at now.

If you're interested, check out the mailing list:
http://lists.x.org/mailman/listinfo/xorg-devel
