### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by SyedOmarNooredu** [galundin/circular-scrolling-improved#2]
i'm new to linux, so i can't figure out the instructions in the other issue.
i really want chiral scroll because it's very intuitive and better than the centre scroll of linux.
i'm using linux mint cinnamon 20.3
my current input lib is libinput/xinput

**Comment by galundin** [comment]
Unfortunately, this probably won't work for you. It was a patch to the source code for a different device driver, called xfree86-driver-synaptics. You would have to obtain that driver's source code, apply this patch and compile it, then install and configure it. Unfortunately, the patch was made nine years ago, so it probably isn't compatible with the latest version of the driver. If you have some programming experience, you could edit the driver source manually to make it work, but it would be very challenging. Also, I never really finished it - it was still missing some features. I quit working on it because I don't use a touchpad any more. I wish I could help you, but I don't have access to it now.

**Comment by SyedOmarNooredu** [comment]
oh well, guess i'll use middle button scroll (better than on windows)
thanks for getting back to me (and rather quick)
